name: Deploy Sanity
on:
  push:
    branches: [main]
jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity
    steps: 
      - uses: actions/checkout@v3
      - name: GitHub Action for npx
        uses: mikeal/npx@1.0.0
      - name: Install packages
        run: npm install --legacy-peer-deps
        working-directory: ./marius-tanker-sanity
      - name: Deploy Sanity
        run: npx sanity deploy
        working-directory: ./marius-tanker-sanity

