name: Deploy Sanity
on:
  push:
    branches: [main]
jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity
    steps: 
      - name: GitHub Action for npx
        uses: mikeal/npx@1.0.0
      - name: Deploy Sanity
        run: npx sanity deploy
        working-directory: marius-tanker-sanity/

